name: app_custom_lints
description: A starting point for Dart libraries or applications.
version: 1.0.0
repository: https://github.com/AlexxyQQ/custom_lints

environment:
  sdk: ^3.9.2

# Add regular dependencies here.
dependencies:
  analyzer: ^8.1.1
  custom_lint_builder: ^0.8.1

dev_dependencies:
  lints: ^6.0.0
  test: ^1.26.3
  very_good_analysis: ^10.0.0
